### PR TITLE
feat: variable files created

### PR DESCRIPTION
**Pull request by emazino**
Kindly review and approve

### CODE REVIEW

**Review by olabola1108 — APPROVED** [review]
Reviewed

**Comment by jndamito** [comment]
Code reviewed and approved

**Review by jndamito — APPROVED** [review]
Code reviewed and approved

**Comment by asuku1510** [comment]
Reviewed

**Review by asuku1510 — COMMENTED** [review]
Reviewed

**Review by asuku1510 — APPROVED** [review]

**Review by BensGits — APPROVED** [review]
aren't we hardcoding some parameter in tgw, vpc modules
- amazon_side_asn
- destination_cidr_block
Good job all

**Review by kingphillips — COMMENTED** [review]
Approved

**Pull request merged**
